'use client';
import { balance, cents, displayDate, money, received, status, today, totals, type WorkspaceData, type Invoice, type Quote, type Settings } from '@digitnepal/shared/billing';
import { Badge } from './billing-forms';
function Business({business}:{business:Settings}) {return <div><h2>{business.name}</h2><p>{business.address}</p><p>{business.email} · {business.phone}</p>{business.taxId&&<p>PAN / VAT: {business.taxId}</p>}</div>;}
export function DocumentPaper({document:d,data,quote=false}:{document:Invoice|Quote;data:WorkspaceData;quote?:boolean}) {
 const total=totals(d);const payments=data.payments.filter(p=>p.invoiceId===d.id&&!p.reversedAt);const invoice=d as Invoice;
 return <article className="invoice-paper"><div className="paper-heading"><Business business={d.business}/><div><span className="paper-label">{quote?'QUOTATION':d.state==='Draft'?'DRAFT INVOICE':d.state==='Void'?'VOID INVOICE':'INVOICE'}</span><h3>{d.number}</h3><Badge value={quote?d.state:status(invoice,data.payments)}/></div></div><div className="paper-parties"><div><span className="paper-label">{quote?'PREPARED FOR':'BILL TO'}</span><h3>{d.client.name}</h3><p>{d.client.email}</p><p>{d.client.address}</p><p>{d.client.phone}</p>{d.client.taxId&&<p>PAN / VAT: {d.client.taxId}</p>}</div><div><p><span>Date</span><strong>{displayDate(d.date)}</strong></p><p><span>{quote?'Valid until':'Due date'}</span><strong>{displayDate(d.dueDate)}</strong></p><p><span>Currency</span><strong>NPR</strong></p>{d.projectId&&<p><span>Project</span><strong>{data.projects.find(p=>p.id===d.projectId)?.name}</strong></p>}</div></div><div className="billing-table-scroll"><table className="paper-table"><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount (NPR)</th></tr></thead><tbody>{d.items.map((item,index)=><tr key={index}><td>{item.description}</td><td>{item.quantity}</td><td>{money(item.rate)}</td><td>{money(cents(item.quantity*item.rate)/100)}</td></tr>)}</tbody></table></div><div className="paper-totals invoice-totals"><div><span>Subtotal</span><strong>{money(total.subtotal)}</strong></div><div><span>Discount</span><strong>− {money(d.discount)}</strong></div><div><span>Tax ({d.taxRate}%)</span><strong>{money(total.tax)}</strong></div><div className="grand-total"><span>Total (NPR)</span><strong>{money(total.total)}</strong></div>{!quote&&d.state==='Issued'&&<><div><span>Received</span><strong>{money(received(invoice,data.payments))}</strong></div><div><span>Balance due</span><strong>{money(balance(invoice,data.payments))}</strong></div></>}</div>
 {!quote&&payments.length>0&&<div className="paper-notes"><span className="paper-label">PAYMENTS RECEIVED</span>{payments.map(p=><p key={p.id}>{displayDate(p.date)} · {p.number} · {p.method} · NPR {money(p.amount)}{p.reference?` · ${p.reference}`:''}</p>)}</div>}
 {d.notes&&<div className="paper-notes"><span className="paper-label">NOTES & TERMS</span><p>{d.notes}</p></div>}
 {d.business.bankName&&<div className="paper-notes"><span className="paper-label">BANK DETAILS</span><p>{d.business.bankName} · {d.business.bankAccountName}<br/>Account: {d.business.bankAccount}</p></div>}
 {!quote&&invoice.voidReason&&<div className="paper-notes"><strong>Voided: {invoice.voidReason}</strong></div>}<footer>{quote?'This quotation is an estimate, not a payment request.':d.state==='Draft'?'Draft for review. This invoice has not been issued.':`Thank you for choosing ${d.business.name}.`}<span>Digit Nepal · Built on trust.</span></footer></article>;
}
export function ReceiptPaper({id,data}:{id:string;data:WorkspaceData}) {const p=data.payments.find(p=>p.id===id)!;const i=data.invoices.find(i=>i.id===p.invoiceId)!;return <article className="invoice-paper"><div className="paper-heading"><Business business={i.business}/><div><span className="paper-label">{p.reversedAt?'REVERSED RECEIPT':'PAYMENT RECEIPT'}</span><h3>{p.number}</h3></div></div><div className="paper-parties"><div><span className="paper-label">RECEIVED FROM</span><h3>{i.client.name}</h3><p>{i.client.email}</p><p>{i.client.address}</p></div><div><p><span>Date</span><strong>{displayDate(p.date)}</strong></p><p><span>Invoice</span><strong>{i.number}</strong></p><p><span>Method</span><strong>{p.method}</strong></p><p><span>Reference</span><strong>{p.reference||'—'}</strong></p></div></div><div className="v2-receipt-amount"><span>Amount received</span><strong>NPR {money(p.amount)}</strong></div>{p.notes&&<div className="paper-notes"><p>{p.notes}</p></div>}{p.reversedAt&&<div className="paper-notes"><strong>Reversed {displayDate(p.reversedAt)}: {p.reversalReason}</strong><p>This receipt no longer counts toward the invoice balance.</p></div>}<footer>Payment recorded by {i.business.name}.<span>Thank you for your business.</span></footer></article>;}
export function StatementPaper({id,data}:{id:string;data:WorkspaceData}) {
 const client=data.clients.find(c=>c.id===id)!;const invoices=data.invoices.filter(i=>i.clientId===id&&i.state==='Issued');
 const entries=[...invoices.map(i=>({id:i.id,date:i.date,reference:i.number,description:'Invoice',debit:totals(i).total,credit:0,order:0})),...data.payments.filter(p=>!p.reversedAt&&invoices.some(i=>i.id===p.invoiceId)).map(p=>({id:p.id,date:p.date,reference:p.number,description:`Payment · ${data.invoices.find(i=>i.id===p.invoiceId)?.number}`,debit:0,credit:p.amount,order:1}))].sort((a,b)=>a.date.localeCompare(b.date)||a.order-b.order||a.reference.localeCompare(b.reference));
 let running=0;const rows=entries.map(e=>({...e,balance:(running+=cents(e.debit)-cents(e.credit))/100}));
 return <article className="invoice-paper"><div className="paper-heading"><Business business={data.settings}/><div><span className="paper-label">CLIENT STATEMENT</span><h3>{displayDate(today())}</h3><p>All transactions · NPR</p></div></div><div className="paper-parties"><div><h3>{client.name}</h3><p>{client.email}</p><p>{client.address}</p></div><div><p><span>Outstanding balance</span><strong>NPR {money(running/100)}</strong></p><p><span>Issued invoices</span><strong>{invoices.length}</strong></p></div></div><div className="billing-table-scroll"><table className="paper-table"><thead><tr><th>Date / reference</th><th>Description</th><th>Invoiced</th><th>Received</th><th>Balance</th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td>{displayDate(e.date)}<br/>{e.reference}</td><td>{e.description}</td><td>{e.debit?money(e.debit):'—'}</td><td>{e.credit?money(e.credit):'—'}</td><td>{money(e.balance)}</td></tr>)}{!rows.length&&<tr><td colSpan={5}>No issued invoices or payments yet.</td></tr>}</tbody></table></div><footer>Statement includes issued invoices and unreversed payments.<span>Drafts and void records are excluded.</span></footer></article>;
}
