import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import pg from 'pg';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const databaseUrl=process.env.BILLING_TEST_DATABASE_URL;
if(!databaseUrl || !new URL(databaseUrl).pathname.endsWith('_test')) throw new Error('Set BILLING_TEST_DATABASE_URL to a dedicated *_test database.');
const pool=new pg.Pool({connectionString:databaseUrl});
await pool.query('DROP TABLE IF EXISTS billing_operations,billing_login_attempts,billing_sessions,billing_users,billing_workspace CASCADE');
const origin=`http://127.0.0.1:${process.env.BILLING_TEST_PORT||3101}`;
const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const add=(d,n)=>new Date(Date.parse(d+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
let server,logs='',cookie='',checks=0;
function check(actual,expected,message){assert.equal(actual,expected,message);checks++;}
async function start(){logs='';server=spawn(process.execPath,[path.join(root,'node_modules/tsx/dist/cli.mjs'),path.join(root,'server/index.ts')],{cwd:path.join(root,'server'),windowsHide:true,env:{...process.env,DATABASE_URL:databaseUrl,FRONTEND_ORIGIN:origin,ADMIN_PASSWORD:'TestAdminPassword123',PORT:new URL(origin).port},stdio:['ignore','pipe','pipe']});server.stdout.on('data',c=>{logs+=c;});server.stderr.on('data',c=>{logs+=c;});for(let n=0;n<100;n++){if(server.exitCode!==null)throw new Error(logs);try{if((await fetch(origin+'/health')).ok)return;}catch{}await new Promise(r=>setTimeout(r,250));}throw new Error('Server failed to start: '+logs);}
async function stop(){if(server&&server.exitCode===null){const ended=once(server,'exit');server.kill();await ended;}}
async function request(route,method='GET',body,extra={}){return fetch(origin+route,{method,redirect:'manual',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json',...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});}
async function post(command,expected=200,requestId=randomUUID()){const r=await request('/api/admin/billing','POST',{...command,requestId});const d=await r.json();check(r.status,expected,JSON.stringify(d));return d;}
async function login(username='admin',password='TestAdminPassword123',expected=200){const r=await request('/api/admin/session','POST',{username,password});check(r.status,expected,await r.clone().text());if(r.ok){const c=r.headers.get('set-cookie');assert.match(c,/HttpOnly/i);assert.match(c,/SameSite=strict/i);cookie=c.split(';')[0];}return r;}
async function get(){const r=await request('/api/admin/billing');check(r.status,200);return r.json();}
try{
 await start();check((await request('/api/admin/billing')).status,401);check((await request('/api/admin/billing/backup')).status,401);
 await login('admin','wrong',401);check((await request('/api/admin/session','POST',{password:'TestAdminPassword123'},{Origin:'https://elsewhere.example'})).status,403);await login();const adminCookie=cookie;
 cookie=cookie.slice(0,-1)+(cookie.endsWith('a')?'b':'a');check((await request('/api/admin/billing')).status,401);cookie=adminCookie;
 check((await request('/api/admin/billing','POST',{}, {Origin:'https://elsewhere.example'})).status,403);
 let data=await get();check(data.version,2);check(data.invoices.length,0);check(data.backup.warning,null);
 const createClient={action:'client.save',value:{name:'=Verification Client',email:'billing@example.com',phone:'+977 9800000001',address:'Kathmandu',taxId:'TEST-123',notes:'QA fixture'}};const duplicateKey=randomUUID();data=await post(createClient,200,duplicateKey);const id=data.clients.at(-1).id;const revision=data.revision;data=await post(createClient,200,duplicateKey);check(data.clients.length,1);check(data.revision,revision);await post({...createClient,value:{...createClient.value,name:'Different'}},409,duplicateKey);await post(createClient,400);
 const input={clientId:id,date:day,dueDate:add(day,14),items:[{description:'Website design',quantity:2,rate:5000,serviceId:''},{description:'Brand assets',quantity:1,rate:2500,serviceId:''}],taxRate:13,discount:500,notes:'Payment within 14 days',projectId:'',milestoneId:''};
 await post({action:'invoice.save',value:{...input,dueDate:add(day,-1)}},400);await post({action:'invoice.save',value:{...input,date:'2026-02-30'}},400);await post({action:'invoice.save',value:{...input,discount:13000}},400);await post({action:'invoice.save',value:{...input,items:[{description:'Too large',quantity:10000,rate:1e9}]}},400);
 data=await post({action:'invoice.save',value:input});let invoice=data.invoices[0];check(invoice.state,'Draft');const invoiceId=invoice.id;
 const pay={invoiceId,amount:5000,date:day,method:'Bank transfer',reference:'TXN-001',notes:'First installment'};
 await post({action:'payment.create',value:pay},400);await post({action:'invoice.save',id:invoiceId,updatedAt:'stale',value:input},409);data=await post({action:'invoice.save',id:invoiceId,updatedAt:invoice.updatedAt,value:{...input,notes:'Updated draft'}});invoice=data.invoices.find(i=>i.id===invoiceId);check(invoice.notes,'Updated draft');data=await post({action:'invoice.issue',id:invoiceId});check(data.invoices.find(i=>i.id===invoiceId).state,'Issued');await post({action:'invoice.save',id:invoiceId,updatedAt:invoice.updatedAt,value:input},400);await post({action:'invoice.issue',id:invoiceId},400);
 const paymentKey=randomUUID();data=await post({action:'payment.create',value:pay},200,paymentKey);const receipt=data.payments[0];data=await post({action:'payment.create',value:pay},200,paymentKey);check(data.payments.filter(p=>p.invoiceId===invoiceId).length,1);await post({action:'payment.create',value:{...pay,amount:8560.01}},400);await post({action:'payment.create',value:{...pay,amount:1,date:add(day,1)}},400);await post({action:'payment.create',value:{...pay,amount:1,date:add(day,-1)}},400);await post({action:'invoice.void',id:invoiceId,reason:'Cannot void with active payments'},400);
 let csv=await (await request('/api/admin/billing/export?status=Part%20paid')).text();assert.match(csv,/8,560|8560/);assert.match(csv,/'=Verification Client/);assert.match(csv,/Part paid/);csv=await (await request('/api/admin/billing/export?search=NO_MATCH')).text();check(csv.includes('Verification'),false);
 data=await post({action:'payment.create',value:{...pay,amount:8560,reference:'TXN-FINAL'}});check(data.payments.filter(p=>p.invoiceId===invoiceId&&!p.reversedAt).reduce((s,p)=>s+p.amount,0),13560);await post({action:'payment.create',value:{...pay,amount:.01}},400);data=await post({action:'payment.reverse',id:receipt.id,reason:'Wrong payment reference'});check(Boolean(data.payments.find(p=>p.id===receipt.id).reversedAt),true);await post({action:'payment.reverse',id:receipt.id,reason:'Repeat reversal'},400);
 data=await post({action:'invoice.duplicate',id:invoiceId});check(data.invoices[0].state,'Draft');const duplicateId=data.invoices[0].id;data=await post({action:'invoice.void',id:duplicateId,reason:'Duplicate no longer needed'});check(data.invoices.find(i=>i.id===duplicateId).state,'Void');
 data=await post({action:'quote.save',value:input});const quoteId=data.quotes[0].id;await post({action:'quote.convert',id:quoteId},400);data=await post({action:'quote.status',id:quoteId,state:'Sent'});data=await post({action:'quote.status',id:quoteId,state:'Accepted'});data=await post({action:'quote.convert',id:quoteId});const convertedId=data.quotes.find(q=>q.id===quoteId).convertedInvoiceId;check(data.invoices.find(i=>i.id===convertedId).state,'Draft');await post({action:'quote.convert',id:quoteId},400);
 const project={clientId:id,name:'Website launch',kind:'Project',budget:40000,startDate:day,dueDate:add(day,60),notes:'Design and development',milestones:[{id:'',title:'Design deposit',amount:10000,dueDate:add(day,7)},{id:'',title:'Final delivery',amount:30000,dueDate:add(day,60)}]};await post({action:'project.create',value:{...project,budget:100}},400);data=await post({action:'project.create',value:project});const projectId=data.projects[0].id;const milestoneId=data.projects[0].milestones[0].id;data=await post({action:'project.bill',id:projectId,milestoneId});check(data.invoices[0].milestoneId,milestoneId);await post({action:'project.bill',id:projectId,milestoneId},400);await post({action:'invoice.save',value:{...input,clientId:'unknown-client',projectId}},404);
 data=await post({action:'project.create',value:{...project,name:'Web development course',kind:'Training'}});check(data.projects.at(-1).kind,'Training');
 data=await post({action:'service.save',value:{name:'Website package',description:'Responsive business website',category:'Development',rate:35000,taxRate:13}});check(data.services.length,1);
 data=await post({action:'expense.create',value:{description:'Hosting',vendor:'Cloud provider',amount:1200,date:day,category:'Hosting',projectId,reference:'EXP-REF'}});const expenseId=data.expenses[0].id;data=await post({action:'expense.void',id:expenseId,reason:'Recorded twice'});check(Boolean(data.expenses.find(e=>e.id===expenseId).voidedAt),true);data=await post({action:'expense.create',value:{description:'Design contractor',vendor:'QA Designer',amount:3500,date:day,category:'Contractors',projectId,reference:'DESIGN'}});
 const jan=`${Number(day.slice(0,4))-1}-01-31`;data=await post({action:'recurring.create',invoiceId,name:'Maintenance',interval:'Monthly',nextDate:jan});const recurringId=data.recurring[0].id;data=await post({action:'recurring.generate',id:recurringId});check(data.recurring[0].nextDate.slice(5,7),'02');data=await post({action:'recurring.generate',id:recurringId});check(data.recurring[0].nextDate.slice(5),'03-31');data=await post({action:'recurring.toggle',id:recurringId,active:false});await post({action:'recurring.generate',id:recurringId},400);
 const settingsBefore=data.settings;await post({action:'settings',value:settingsBefore,revision:-1},409);data=await post({action:'settings',revision:data.revision,value:{...settingsBefore,bankName:'Demo Bank',bankAccount:'123456789',bankAccountName:'Digit Nepal',paymentTerms:'Payment within 14 days.'}});check(data.invoices.find(i=>i.id===invoiceId).business.bankName,'');
 const concurrent=await Promise.all(Array.from({length:5},()=>post({action:'invoice.save',value:input})));const ids=concurrent.flatMap(d=>d.invoices.map(i=>i.number));data=await get();check(new Set(data.invoices.map(i=>i.number)).size,data.invoices.length);assert.ok(ids.length>0);
 data=await post({action:'user.create',value:{username:'viewer',name:'Review User',role:'Viewer',password:'ViewerPassword123'}});const viewerId=data.users.find(u=>u.username==='viewer').id;data=await post({action:'user.create',value:{username:'accountant',name:'Accounts User',role:'Accountant',password:'AccountPassword123'}});await post({action:'user.toggle',id:data.currentUser.id,active:false},400);
 await login('viewer','ViewerPassword123');data=await get();check(data.users.length,0);await post({action:'client.save',value:{...createClient.value,email:'viewer@example.com'}},403);check((await request('/api/admin/billing/backup')).status,403);check((await request('/api/admin/billing/export')).status,200);const viewerCookie=cookie;
 await login('accountant','AccountPassword123');data=await get();await post({action:'settings',revision:data.revision,value:data.settings},403);await post({action:'user.create',value:{username:'blocked',name:'Blocked',role:'Admin',password:'VeryLongPassword'}},403);data=await post({action:'client.save',value:{name:'Accountant Client',email:'accountant@example.com',phone:'',address:''}});check(data.clients.some(c=>c.email==='accountant@example.com'),true);
 cookie=adminCookie;data=await post({action:'user.toggle',id:viewerId,active:false});cookie=viewerCookie;check((await request('/api/admin/billing')).status,401);await login('viewer','ViewerPassword123',401);cookie=adminCookie;data=await post({action:'user.toggle',id:viewerId,active:true});
 const competing=await Promise.all(Array.from({length:2},()=>request('/api/admin/billing','POST',{action:'payment.create',value:{...pay,amount:5000,reference:'Concurrent settlement'},requestId:randomUUID()})));check(competing.filter(r=>r.status===200).length,1);check(competing.filter(r=>r.status===400).length,1);data=await get();
 const duplicatePaymentKey=randomUUID();const repeated=await Promise.all(Array.from({length:2},()=>post({action:'client.save',value:{name:'Concurrent retry',email:'retry@example.com',phone:'',address:''}},200,duplicatePaymentKey)));check(repeated[1].clients.filter(c=>c.email==='retry@example.com').length,1);data=await get();
 const exportResponse=await request('/api/admin/billing/backup');check(exportResponse.status,200);const backup=await exportResponse.json();check(backup.workspace.version,2);check(JSON.stringify(backup).includes('password_hash'),false);check(JSON.stringify(backup).includes('TestAdminPassword123'),false);
 await stop();await start();data=await get();check(data.invoices.some(i=>i.id===invoiceId),true);check(data.payments.some(p=>p.id===receipt.id&&p.reversedAt),true);check(data.users.length,3);
 await post({action:'password',currentPassword:'bad',newPassword:'ChangedAdminPassword123'},400);await post({action:'password',currentPassword:'TestAdminPassword123',newPassword:'ChangedAdminPassword123'});check((await request('/api/admin/billing')).status,401);await login('admin','TestAdminPassword123',401);await login('admin','ChangedAdminPassword123');check((await request('/api/admin/session','DELETE')).status,200);check((await request('/api/admin/billing')).status,401);
 for(let n=0;n<5;n++)await login('unknown','bad',401);await login('unknown','bad',429);
 console.log(`PASS: ${checks} billing checks, including lifecycle, roles, exports and PostgreSQL persistence.`);
} catch(error){console.error(logs);throw error;} finally {await stop();await pool.end();}
