'use client';
import { useEffect, useRef, useState, type ReactNode, type FormEvent } from 'react';
import { X, Plus, Trash2 } from 'lucide-react';
import { addDays, balance, money, today, totals, type WorkspaceData, type InvoiceInput, type Invoice, type Quote } from '@/lib/admin/billing';
import type { Command } from '@/lib/admin/commands';
export function Field({label,children}:{label:string;children:ReactNode}) { return <label className="billing-field"><span>{label}</span>{children}</label>; }
export function ModalFrame({title,children,onClose,busy=false,print=false}:{title:string;children:ReactNode;onClose:()=>void;busy?:boolean;print?:boolean}) {
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const dialog=ref.current; const prior=document.activeElement as HTMLElement;dialog?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{dialog?.close();document.body.style.overflow=previous;prior?.focus();};},[]);
 return <dialog ref={ref} className={`billing-modal ${print?'invoice-view':''}`} aria-label={title} onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="modal-inner"><header className="modal-header no-print"><div><span className="billing-eyebrow">DIGIT NEPAL • BILLING STUDIO</span><h2>{title}</h2></div><button className="billing-icon-button" aria-label="Close dialog" disabled={busy} onClick={onClose}><X size={20}/></button></header>{children}</div></dialog>;
}
export function Badge({value}:{value:string}) {return <span className={`v2-badge ${value.toLowerCase().replaceAll(' ','-')}`}>{value}</span>;}
export function Empty({title,detail,children}:{title:string;detail:string;children?:ReactNode}) {return <div className="v2-empty"><div className="empty-icon"><Plus size={24}/></div><h3>{title}</h3><p>{detail}</p>{children}</div>;}
export type Save=(command:Command)=>Promise<boolean>;
export type FormKind='client'|'project'|'service'|'expense'|'payment'|'recurring'|'user'|'password'|'reason';
type InputSpec={key:string;label:string;type?:string;options?:{value:string;label:string}[];required?:boolean;value?:string|number;min?:string|number;max?:string|number};
const opts=(values:string[])=>values.map(value=>({value,label:value}));
export function SimpleForm({kind,data,id,action,onSave,busy}:{kind:FormKind;data:WorkspaceData;id?:string;action?:string;onSave:Save;busy:boolean}) {
 const client=data.clients.find(c=>c.id===id); const service=data.services.find(s=>s.id===id);
 const [invoiceId,setInvoiceId]=useState(id||data.invoices.find(i=>balance(i,data.payments)>0)?.id||'');
 const invoice=data.invoices.find(i=>i.id===invoiceId);
 const [milestones,setMilestones]=useState<{id:string;title:string;amount:number;dueDate:string}[]>([]);
 const clients=data.clients.map(c=>({value:c.id,label:c.name}));const projects=[{value:'',label:'No project'},...data.projects.map(p=>({value:p.id,label:p.name}))];
 let specs:InputSpec[]=[];
 if(kind==='client') specs=[{key:'name',label:'Client / company name',value:client?.name},{key:'email',label:'Email address',type:'email',value:client?.email},{key:'phone',label:'Phone',required:false,value:client?.phone},{key:'taxId',label:'PAN / VAT number',required:false,value:client?.taxId},{key:'address',label:'Address',required:false,value:client?.address},{key:'notes',label:'Internal notes',type:'textarea',required:false,value:client?.notes}];
 if(kind==='service') specs=[{key:'name',label:'Service name',value:service?.name},{key:'category',label:'Category',options:opts(['Development','Design','Hosting','Maintenance','Training','Other']),value:service?.category},{key:'description',label:'Invoice description',value:service?.description},{key:'rate',label:'Unit price (NPR)',type:'number',value:service?.rate??0},{key:'taxRate',label:'Default tax (%)',type:'number',max:100,value:service?.taxRate??0}];
 if(kind==='expense') specs=[{key:'description',label:'Expense description'},{key:'vendor',label:'Vendor / payee',required:false},{key:'amount',label:'Amount paid (NPR)',type:'number',min:.01},{key:'date',label:'Payment date',type:'date',value:today(),max:today()},{key:'category',label:'Category',options:opts(['Hosting','Contractors','Software','Office','Travel','Other'])},{key:'projectId',label:'Project',options:projects,required:false},{key:'reference',label:'Reference / voucher number',required:false}];
 if(kind==='project') specs=[{key:'name',label:'Project / course name'},{key:'clientId',label:'Client / student',options:clients},{key:'kind',label:'Billing type',options:opts(['Project','Training'])},{key:'budget',label:'Agreed budget before tax (NPR)',type:'number'},{key:'startDate',label:'Start date',type:'date',value:today()},{key:'dueDate',label:'End date',type:'date',value:addDays(today(),30)},{key:'notes',label:'Scope / enrollment notes',type:'textarea',required:false}];
 if(kind==='payment') specs=[{key:'amount',label:'Amount received (NPR)',type:'number',min:.01,max:invoice?balance(invoice,data.payments):undefined,value:invoice?balance(invoice,data.payments):0},{key:'date',label:'Received on',type:'date',min:invoice?.date,max:today(),value:today()},{key:'method',label:'Payment method',options:opts(['Bank transfer','Cash','eSewa','Khalti','Other'])},{key:'reference',label:'Transaction reference',required:false},{key:'notes',label:'Payment notes',type:'textarea',required:false}];
 if(kind==='recurring') specs=[{key:'invoiceId',label:'Copy line items from issued invoice',options:data.invoices.filter(i=>i.state==='Issued').map(i=>({value:i.id,label:`${i.number} · ${i.client.name}`}))},{key:'name',label:'Schedule name'},{key:'interval',label:'Repeat',options:opts(['Monthly','Yearly'])},{key:'nextDate',label:'Next bill date',type:'date',value:addDays(today(),30)}];
 if(kind==='user') specs=[{key:'name',label:'Full name'},{key:'username',label:'Username (3–40 letters, numbers, . _ -)'},{key:'role',label:'Access role',options:opts(['Accountant','Viewer','Admin'])},{key:'password',label:'Initial password (at least 10 characters)',type:'password'}];
 if(kind==='password') specs=[{key:'currentPassword',label:'Current password',type:'password'},{key:'newPassword',label:'New password (at least 10 characters)',type:'password'}];
 if(kind==='reason') specs=[{key:'reason',label:'Reason (required for the audit trail)',type:'textarea'}];
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const value=Object.fromEntries(specs.map(s=>[s.key,s.type==='number'?Number(form.get(s.key)):String(form.get(s.key)||'')]));
 let command:unknown;
 if(kind==='client'||kind==='service') command={action:`${kind}.save`,id,value};
 if(kind==='project') command={action:'project.create',value:{...value,milestones}};
 if(kind==='expense') command={action:'expense.create',value};
 if(kind==='payment') command={action:'payment.create',value:{...value,invoiceId}};
 if(kind==='recurring') command={action:'recurring.create',...value};
 if(kind==='user') command={action:'user.create',value};
 if(kind==='password') command={action:'password',...value};
 if(kind==='reason') command={action,id,...value};
 await onSave(command as Command);
 }
 return <form className="v2-form" onSubmit={submit}><fieldset disabled={busy}><div className="billing-form-grid">
 {kind==='payment'&&<Field label="Invoice"><select value={invoiceId} required onChange={e=>setInvoiceId(e.target.value)}><option value="" disabled>Select an invoice</option>{data.invoices.filter(i=>balance(i,data.payments)>0).map(i=><option key={i.id} value={i.id}>{i.number} · {i.client.name} · NPR {money(balance(i,data.payments))} due</option>)}</select></Field>}
 {specs.map(s=><Field key={`${s.key}-${kind==='payment'?invoiceId:''}`} label={s.label}>{s.options?<select name={s.key} defaultValue={s.value} required={s.required!==false}>{s.options.length===0&&<option value="">Create a {kind==='recurring'?'issued invoice':'client'} first</option>}{s.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:s.type==='textarea'?<textarea name={s.key} rows={3} defaultValue={s.value} required={s.required!==false} maxLength={kind==='reason'?500:2000}/>:<input name={s.key} type={s.type||'text'} defaultValue={s.value} required={s.required!==false} min={s.min??(s.type==='number'?0:undefined)} max={s.max??(s.type==='number'?1e9:undefined)} step={s.type==='number'?'.01':undefined} minLength={s.type==='password'&&s.key!=='currentPassword'?10:undefined} autoComplete={s.type==='password'?(s.key==='currentPassword'?'current-password':'new-password'):undefined} maxLength={s.type==='password'?200:300}/>}</Field>)}
 </div>
 {kind==='project'&&<div className="v2-milestones"><div className="v2-row"><div><h3>Milestones & installments</h3><p>Split the agreed budget into billable stages.</p></div><button type="button" className="billing-secondary" disabled={milestones.length>=24} onClick={()=>setMilestones([...milestones,{id:'',title:'',amount:0,dueDate:addDays(today(),14)}])}><Plus size={16}/> Add stage</button></div>{milestones.map((m,index)=><div className="v2-stage" key={index}><Field label={`Stage ${index+1}`}><input required value={m.title} onChange={e=>setMilestones(milestones.map((v,i)=>i===index?{...v,title:e.target.value}:v))}/></Field><Field label="Amount (NPR)"><input required type="number" min="0.01" step=".01" value={m.amount} onChange={e=>setMilestones(milestones.map((v,i)=>i===index?{...v,amount:Number(e.target.value)}:v))}/></Field><Field label="Due date"><input required type="date" value={m.dueDate} onChange={e=>setMilestones(milestones.map((v,i)=>i===index?{...v,dueDate:e.target.value}:v))}/></Field><button type="button" className="billing-icon-button" aria-label={`Remove stage ${index+1}`} onClick={()=>setMilestones(milestones.filter((_,i)=>i!==index))}><Trash2 size={16}/></button></div>)}</div>}
 {kind==='recurring'&&<p className="v2-help">Schedules create drafts when you choose “Generate draft”. Review tax, dates and amounts before issuing. No payment is charged automatically.</p>}
 {kind==='payment'&&<p className="v2-help">Record money already received. This does not charge the client.</p>}
 {kind==='reason'&&<p className="v2-help">This record stays in your history. Reversing a payment updates the ledger; it does not refund money.</p>}
 {kind==='user'&&<p className="v2-help">Accountants manage billing. Viewers can only read and export. Admins also manage company details, accounts and backups.</p>}
 <div className="v2-form-footer"><button className="billing-primary" disabled={busy}>{busy?'Saving…':kind==='payment'?'Record payment':kind==='reason'?'Confirm change':kind==='password'?'Change password & sign out':'Save '+(kind==='user'?'account':kind)}</button></div></fieldset></form>;
}
export function DocumentForm({data,kind,existing,onSave,busy}:{data:WorkspaceData;kind:'invoice'|'quote';existing?:Invoice|Quote;onSave:Save;busy:boolean}) {
 const [value,setValue]=useState<InvoiceInput>(existing||{clientId:data.clients[0]?.id||'',date:today(),dueDate:addDays(today(),14),items:[{description:'',quantity:1,rate:0,serviceId:''}],taxRate:0,discount:0,notes:data.settings.paymentTerms,projectId:'',milestoneId:''});
 const total=totals(value);const patch=(p:Partial<InvoiceInput>)=>setValue(v=>({...v,...p}));
 return <form className="v2-form" onSubmit={e=>{e.preventDefault();void onSave({action:kind==='invoice'?'invoice.save':'quote.save',id:existing?.id,updatedAt:existing?.updatedAt,value});}}><fieldset disabled={busy}><div className="billing-form-grid"><Field label="Client"><select required value={value.clientId} onChange={e=>patch({clientId:e.target.value,projectId:'',milestoneId:''})}><option value="" disabled>Select client</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Project (optional)"><select value={value.projectId} onChange={e=>patch({projectId:e.target.value,milestoneId:''})}><option value="">No project</option>{data.projects.filter(p=>p.clientId===value.clientId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label={kind==='quote'?'Quotation date':'Invoice date'}><input type="date" required value={value.date} onChange={e=>patch({date:e.target.value})}/></Field><Field label={kind==='quote'?'Valid until':'Payment due'}><input type="date" required min={value.date} value={value.dueDate} onChange={e=>patch({dueDate:e.target.value})}/></Field></div>
 <div className="v2-row v2-line-heading"><h3>Services & line items</h3><button type="button" className="billing-secondary" disabled={value.items.length>=30} onClick={()=>patch({items:[...value.items,{description:'',quantity:1,rate:0,serviceId:''}]})}><Plus size={16}/> Add line</button></div>
 {value.items.map((item,index)=><div className="v2-line" key={index}><div className="v2-line-description"><Field label={`Description ${index+1}`}><input required maxLength={160} value={item.description} onChange={e=>patch({items:value.items.map((v,i)=>i===index?{...v,description:e.target.value}:v)})}/></Field>{data.services.length>0&&<select aria-label={`Service for line ${index+1}`} value={item.serviceId} onChange={e=>{const s=data.services.find(s=>s.id===e.target.value);if(s)patch({items:value.items.map((v,i)=>i===index?{...v,description:s.description,rate:s.rate,serviceId:s.id}:v),...(value.items.length===1?{taxRate:s.taxRate}:{})});}}><option value="">Choose from service catalog</option>{data.services.map(s=><option key={s.id} value={s.id}>{s.name} · NPR {money(s.rate)}</option>)}</select>}</div><Field label="Qty"><input type="number" min="0.01" max="10000" step=".01" required value={item.quantity} onChange={e=>patch({items:value.items.map((v,i)=>i===index?{...v,quantity:Number(e.target.value)}:v)})}/></Field><Field label="Rate (NPR)"><input type="number" min="0" max="10000000" step=".01" required value={item.rate} onChange={e=>patch({items:value.items.map((v,i)=>i===index?{...v,rate:Number(e.target.value)}:v)})}/></Field><button type="button" className="billing-icon-button" aria-label={`Remove line ${index+1}`} disabled={value.items.length===1} onClick={()=>patch({items:value.items.filter((_,i)=>i!==index)})}><Trash2 size={17}/></button></div>)}
 <div className="billing-form-grid"><Field label="Discount (NPR, before tax)"><input required type="number" min="0" max={total.subtotal} step=".01" value={value.discount} onChange={e=>patch({discount:Number(e.target.value)})}/></Field><Field label="Tax on all lines (%)"><input required type="number" min="0" max="100" step=".01" value={value.taxRate} onChange={e=>patch({taxRate:Number(e.target.value)})}/></Field></div><Field label="Notes & payment terms"><textarea rows={3} maxLength={2000} value={value.notes} onChange={e=>patch({notes:e.target.value})}/></Field><div className="v2-total"><span>Subtotal <b>NPR {money(total.subtotal)}</b></span><span>Tax <b>NPR {money(total.tax)}</b></span><strong>Total <b>NPR {money(total.total)}</b></strong></div><div className="v2-form-footer"><p className="v2-help">Saved as a draft. Review before {kind==='quote'?'marking it sent':'issuing it'}.</p><button className="billing-primary">{busy?'Saving…':'Save draft'}</button></div></fieldset></form>;
}
